# Generated by Django 2.2.3 on 2019-09-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('release', models.IntegerField()),
            ],
        ),
    ]
