# Generated by Django 2.2.3 on 2019-09-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='skills',
            field=models.ManyToManyField(to='main_app.Skill'),
        ),
    ]
